name: granap
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python
  - pip
  - git
  - geopandas
  - ipykernel
  - lxml
  - matplotlib
  - numpy
  - pandas
  - scikit-learn # not sure if it is still needed
  - scipy
  - shapely
  - opencv
  - pip:
    - "-e ..[doc]"
